using NaughtyAttributes;
using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.XR.Interaction.Toolkit;
using UnityEngine.XR.Interaction.Toolkit.Interactors;

namespace GameplayIngredients.Events
{
    public class OnButtonDownEvent : EventBase
    {
        [Header("XR")]
        [Tooltip("XR Direct Interactor that will drive the button events (left or right hand).")]
        public XRDirectInteractor handInteractor;

        [Header("Input System")]
        [Tooltip("Input Actions asset generated by the new Input System.")]
        public InputActionAsset inputActions;

        [Tooltip("Name of the Action Map (e.g. 'XRI Right Interaction' or 'XRI Left Interaction').")]
        public string actionMapName;

        [Tooltip("Name of the Action inside the Action Map (e.g. 'Activate').")]
        public string actionName;

        [Header("Events")]
        [ReorderableList] public Callable[] OnButtonDown;
        [ReorderableList] public Callable[] OnButtonUp;

        [Header("Runtime Control")]
        [Tooltip("Enables or disables the internal logic without touching the Input Action Map.")]
        public bool isActive = true;

        private InputActionMap _map;
        private InputAction _action;

        private void Awake()
        {
            if (inputActions == null)
            {
                Debug.LogError("[OnButtonDownEvent] No InputActionAsset assigned.");
                return;
            }

            _map = inputActions.FindActionMap(actionMapName, false);
            if (_map == null)
            {
                Debug.LogError($"[OnButtonDownEvent] Action Map '{actionMapName}' not found.");
                return;
            }

            _action = _map.FindAction(actionName, false);
            if (_action == null)
            {
                Debug.LogError($"[OnButtonDownEvent] Action '{actionName}' not found in map '{actionMapName}'.");
                return;
            }

            // IMPORTANT: We never enable/disable the Action Map here.
            _action.started += OnActionStarted;
            _action.canceled += OnActionCanceled;
        }

        private void OnDestroy()
        {
            if (_action != null)
            {
                _action.started -= OnActionStarted;
                _action.canceled -= OnActionCanceled;
            }
        }

        // ---------------------------------------------------------
        // Methods callable from Select Entered / Select Exited
        // ---------------------------------------------------------
        public void EnableInput()
        {
            isActive = true;
        }

        public void DisableInput()
        {
            isActive = false;
        }

        // ---------------------------------------------------------
        // Input handling
        // ---------------------------------------------------------
        private void OnActionStarted(InputAction.CallbackContext ctx)
        {
            if (!isActive) return;

            // Check if the hand is holding something
            if (handInteractor != null && handInteractor.hasSelection)
            {
                var selected = handInteractor.firstInteractableSelected;
                if (selected != null)
                {
                    // Trigger events on the held object
                    Callable.Call(OnButtonDown, selected.transform.gameObject);
                }
            }
        }

        private void OnActionCanceled(InputAction.CallbackContext ctx)
        {
            if (!isActive) return;

            if (handInteractor != null && handInteractor.hasSelection)
            {
                var selected = handInteractor.firstInteractableSelected;
                if (selected != null)
                {
                    Callable.Call(OnButtonUp, selected.transform.gameObject);
                }
            }
        }
    }
}
